# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='bind',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
