# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carservices', '0002_wxuser_bind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('bearing', models.CharField(max_length=200)),
                ('speed', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carservices.Account')),
            ],
        ),
    ]
